CREATE TABLE `accounts` (
  `id` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(120) NOT NULL,
  `time_zone` VARCHAR(64) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `devices` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `device_registration_id` VARCHAR(128) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `platform` ENUM('MACOS', 'WINDOWS', 'LINUX') NOT NULL,
  `status` ENUM('ACTIVE', 'OFFLINE', 'REVOKED') NOT NULL DEFAULT 'ACTIVE',
  `last_seen_at` DATETIME(6) NULL,
  `last_synced_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_devices_account_registration` (`account_id`, `device_registration_id`),
  KEY `ix_devices_account_status` (`account_id`, `status`),
  CONSTRAINT `fk_devices_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_tokens` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `device_id` VARCHAR(64) NOT NULL,
  `token_hmac` CHAR(64) NOT NULL,
  `label` VARCHAR(120) NOT NULL,
  `expires_at` DATETIME(6) NULL,
  `revoked_at` DATETIME(6) NULL,
  `last_used_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_device_tokens_hmac` (`token_hmac`),
  KEY `ix_device_tokens_account_device` (`account_id`, `device_id`),
  CONSTRAINT `fk_device_tokens_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_device_tokens_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sync_batches` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `device_id` VARCHAR(64) NOT NULL,
  `batch_id` VARCHAR(128) NOT NULL,
  `protocol_version` INT UNSIGNED NOT NULL,
  `source_type` ENUM('CODEX', 'CLAUDE_CODE') NOT NULL,
  `source_instance_id` VARCHAR(128) NOT NULL,
  `parser_version` VARCHAR(64) NOT NULL,
  `payload_hash` CHAR(64) NOT NULL,
  `status` ENUM('RECEIVED', 'COMMITTED', 'COMMITTED_WITH_WARNINGS', 'FAILED') NOT NULL DEFAULT 'RECEIVED',
  `received_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `inserted_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `duplicate_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `changed_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `result` JSON NULL,
  `received_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `committed_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sync_batches_account_device_batch` (`account_id`, `device_id`, `batch_id`),
  KEY `ix_sync_batches_device_received` (`device_id`, `received_at`),
  CONSTRAINT `fk_sync_batches_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_sync_batches_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `projects` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `normalized_git_remote` VARCHAR(512) NULL,
  `classification_source` ENUM('MANUAL', 'MAPPING_RULE', 'GIT_REMOTE', 'GIT_ROOT', 'WORKING_DIRECTORY', 'SOURCE_HINT', 'UNCLASSIFIED') NOT NULL DEFAULT 'UNCLASSIFIED',
  `confidence_basis_points` INT UNSIGNED NOT NULL DEFAULT 0,
  `is_manual_override` BOOLEAN NOT NULL DEFAULT FALSE,
  `archived_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_projects_account_git_remote` (`account_id`, `normalized_git_remote`),
  KEY `ix_projects_account_name` (`account_id`, `name`),
  CONSTRAINT `chk_projects_confidence` CHECK (`confidence_basis_points` <= 10000),
  CONSTRAINT `fk_projects_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sessions` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `device_id` VARCHAR(64) NOT NULL,
  `project_id` VARCHAR(64) NULL,
  `source_type` ENUM('CODEX', 'CLAUDE_CODE') NOT NULL,
  `source_instance_id` VARCHAR(128) NOT NULL,
  `source_session_id` VARCHAR(255) NOT NULL,
  `parser_version` VARCHAR(64) NOT NULL,
  `started_at` DATETIME(6) NULL,
  `ended_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sessions_source_identity` (`account_id`, `source_type`, `source_instance_id`, `source_session_id`),
  KEY `ix_sessions_account_project_started` (`account_id`, `project_id`, `started_at`),
  KEY `ix_sessions_device` (`device_id`),
  CONSTRAINT `fk_sessions_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_sessions_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_sessions_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `collected_events` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `device_id` VARCHAR(64) NOT NULL,
  `sync_batch_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `project_id` VARCHAR(64) NULL,
  `event_id` CHAR(64) NOT NULL,
  `kind` ENUM('USER_PROMPT', 'VISIBLE_RESULT') NOT NULL,
  `source_message_id` VARCHAR(255) NULL,
  `message_index` INT UNSIGNED NOT NULL,
  `reply_to_event_id` CHAR(64) NULL,
  `occurred_at` DATETIME(6) NOT NULL,
  `source_time_zone` VARCHAR(64) NOT NULL,
  `content_hash` CHAR(64) NOT NULL,
  `current_version` INT UNSIGNED NOT NULL DEFAULT 1,
  `redaction_version` VARCHAR(32) NOT NULL,
  `metadata` JSON NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_collected_events_account_event` (`account_id`, `event_id`),
  KEY `ix_collected_events_session_order` (`session_id`, `message_index`),
  KEY `ix_collected_events_account_occurred` (`account_id`, `occurred_at`),
  KEY `ix_collected_events_device` (`device_id`),
  KEY `ix_collected_events_sync_batch` (`sync_batch_id`),
  KEY `ix_collected_events_project` (`project_id`),
  CONSTRAINT `fk_collected_events_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_collected_events_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_collected_events_sync_batch` FOREIGN KEY (`sync_batch_id`) REFERENCES `sync_batches` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_collected_events_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_collected_events_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `event_versions` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `collected_event_id` VARCHAR(64) NOT NULL,
  `version` INT UNSIGNED NOT NULL,
  `content_hash` CHAR(64) NOT NULL,
  `sanitized_content` LONGTEXT NOT NULL,
  `parser_version` VARCHAR(64) NOT NULL,
  `redaction_version` VARCHAR(32) NOT NULL,
  `metadata` JSON NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_event_versions_event_version` (`collected_event_id`, `version`),
  UNIQUE KEY `uq_event_versions_event_hash` (`collected_event_id`, `content_hash`),
  KEY `ix_event_versions_account` (`account_id`),
  CONSTRAINT `fk_event_versions_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_event_versions_event` FOREIGN KEY (`collected_event_id`) REFERENCES `collected_events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `prompt_entries` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `collected_event_id` VARCHAR(64) NOT NULL,
  `device_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `project_id` VARCHAR(64) NULL,
  `occurred_at` DATETIME(6) NOT NULL,
  `source_time_zone` VARCHAR(64) NOT NULL,
  `sanitized_content` LONGTEXT NOT NULL,
  `content_hash` CHAR(64) NOT NULL,
  `model` VARCHAR(128) NULL,
  `is_favorite` BOOLEAN NOT NULL DEFAULT FALSE,
  `is_manual_project_override` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_prompt_entries_account_event` (`account_id`, `collected_event_id`),
  KEY `ix_prompt_entries_account_occurred` (`account_id`, `occurred_at`),
  KEY `ix_prompt_entries_project_occurred` (`project_id`, `occurred_at`),
  KEY `ix_prompt_entries_device_occurred` (`device_id`, `occurred_at`),
  KEY `ix_prompt_entries_session` (`session_id`),
  FULLTEXT KEY `ft_prompt_entries_content` (`sanitized_content`) WITH PARSER ngram,
  CONSTRAINT `fk_prompt_entries_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_prompt_entries_event` FOREIGN KEY (`collected_event_id`) REFERENCES `collected_events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_prompt_entries_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_prompt_entries_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_prompt_entries_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `visible_results` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `collected_event_id` VARCHAR(64) NOT NULL,
  `prompt_entry_id` VARCHAR(64) NULL,
  `device_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `project_id` VARCHAR(64) NULL,
  `occurred_at` DATETIME(6) NOT NULL,
  `sanitized_content` LONGTEXT NOT NULL,
  `content_hash` CHAR(64) NOT NULL,
  `model` VARCHAR(128) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_visible_results_account_event` (`account_id`, `collected_event_id`),
  KEY `ix_visible_results_prompt` (`prompt_entry_id`),
  KEY `ix_visible_results_account_occurred` (`account_id`, `occurred_at`),
  KEY `ix_visible_results_device` (`device_id`),
  KEY `ix_visible_results_session` (`session_id`),
  KEY `ix_visible_results_project` (`project_id`),
  CONSTRAINT `fk_visible_results_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_visible_results_event` FOREIGN KEY (`collected_event_id`) REFERENCES `collected_events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_visible_results_prompt` FOREIGN KEY (`prompt_entry_id`) REFERENCES `prompt_entries` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_visible_results_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_visible_results_session` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_visible_results_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `daily_summaries` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `work_date` DATE NOT NULL,
  `time_zone` VARCHAR(64) NOT NULL,
  `revision` INT UNSIGNED NOT NULL,
  `status` ENUM('WAITING', 'COMPLETE', 'PARTIAL', 'STALE', 'REGENERATING', 'FAILED') NOT NULL,
  `input_fingerprint` CHAR(64) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `coverage` JSON NOT NULL,
  `model_provider` VARCHAR(64) NULL,
  `model_name` VARCHAR(128) NULL,
  `template_version` VARCHAR(64) NOT NULL,
  `is_manually_edited` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_daily_summaries_account_date_revision` (`account_id`, `work_date`, `revision`),
  UNIQUE KEY `uq_daily_summaries_account_date_fingerprint` (`account_id`, `work_date`, `input_fingerprint`),
  CONSTRAINT `fk_daily_summaries_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `summary_evidence` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `summary_id` VARCHAR(64) NOT NULL,
  `collected_event_id` VARCHAR(64) NOT NULL,
  `claim_key` VARCHAR(128) NOT NULL,
  `claim_type` ENUM('FACT', 'INFERENCE', 'SUGGESTION', 'INFORMATION_MISSING') NOT NULL,
  `excerpt` TEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_summary_evidence_claim_event` (`summary_id`, `claim_key`, `collected_event_id`),
  KEY `ix_summary_evidence_account_event` (`account_id`, `collected_event_id`),
  CONSTRAINT `fk_summary_evidence_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_summary_evidence_summary` FOREIGN KEY (`summary_id`) REFERENCES `daily_summaries` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_summary_evidence_event` FOREIGN KEY (`collected_event_id`) REFERENCES `collected_events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `skill_candidates` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `project_id` VARCHAR(64) NULL,
  `name` VARCHAR(160) NOT NULL,
  `slug` VARCHAR(160) NOT NULL,
  `description` TEXT NOT NULL,
  `status` ENUM('CANDIDATE', 'IN_REVIEW', 'ACCEPTED', 'IGNORED') NOT NULL DEFAULT 'CANDIDATE',
  `evidence_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `proposal` JSON NOT NULL,
  `baseline_hash` CHAR(64) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_skill_candidates_account_slug` (`account_id`, `slug`),
  KEY `ix_skill_candidates_account_status` (`account_id`, `status`),
  KEY `ix_skill_candidates_project` (`project_id`),
  CONSTRAINT `fk_skill_candidates_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_skill_candidates_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `audit_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` VARCHAR(64) NULL,
  `device_id` VARCHAR(64) NULL,
  `action` VARCHAR(128) NOT NULL,
  `resource_type` VARCHAR(64) NOT NULL,
  `resource_id` VARCHAR(128) NULL,
  `request_id` VARCHAR(128) NULL,
  `outcome` ENUM('SUCCEEDED', 'FAILED', 'DENIED') NOT NULL,
  `metadata` JSON NOT NULL,
  `occurred_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `ix_audit_logs_account_occurred` (`account_id`, `occurred_at`),
  KEY `ix_audit_logs_request` (`request_id`),
  KEY `ix_audit_logs_device` (`device_id`),
  CONSTRAINT `fk_audit_logs_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_logs_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
