CREATE TABLE `period_summaries` (
  `id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `period_type` ENUM('WEEK', 'MONTH') NOT NULL,
  `period_start` DATE NOT NULL,
  `period_end` DATE NOT NULL,
  `time_zone` VARCHAR(64) NOT NULL,
  `revision` INT UNSIGNED NOT NULL,
  `status` ENUM('WAITING', 'COMPLETE', 'PARTIAL', 'STALE', 'REGENERATING', 'FAILED') NOT NULL,
  `input_fingerprint` CHAR(64) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `coverage` JSON NOT NULL,
  `model_provider` VARCHAR(64) NULL,
  `model_name` VARCHAR(128) NULL,
  `template_version` VARCHAR(64) NOT NULL,
  `is_manually_edited` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_period_summaries_account_period_revision` (`account_id`, `period_type`, `period_start`, `revision`),
  UNIQUE KEY `uq_period_summaries_account_period_fingerprint` (`account_id`, `period_type`, `period_start`, `input_fingerprint`),
  KEY `ix_period_summaries_account_end` (`account_id`, `period_end`),
  CONSTRAINT `chk_period_summaries_range` CHECK (`period_end` >= `period_start`),
  CONSTRAINT `fk_period_summaries_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
